### ISSUE TITLE
Спроектировать сущность ресурса каталога

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-server#1]
### Вводное сообщение
Каталог состоит из разделов и ресурсов. Каждый раздел может содержать как подразделы, так и ресурсы.

> #### Ресурс
> Ресурс - это некоторая единица информации в каталоге. Например, ресурсом может быть статья или текст. Разумеется, ресурс не может содержать подразделов, ресурсы являются листьями в дереве каталога.

> #### Раздел
> Раздел - самая обыкновенная папка. Разделы исполняют роль контейнеров, позволяющих разделять и обобщать ресурсы в имеющие смысл группы.

Сам по себе каталог тоже является (корневым) разделом. То есть всегда существует некоторый root каталог, который невозможно удалить, но в котором можно создавать подразделы и ресурсы.

### Задание
Продумать и изложить здесь в виде комментария, какие свойства будут у сущности ресурса каталога.
Например, как выше уже упоминалось, у ресурса точно будет свойство 'текст' (название не окончательное, предложения приветствуются и очень поощряются). Также ресурс как-то должен будет 'знать' о своём родительском каталоге, а вот родитель 'знать' о ресурсе не обязан.

### Что ожидается от вас
**Строгого формата нет**, но ваши предложения _могут примерно_ выглядеть как-то так:

> Свойство: `content` 
> Тип: `String`
> Описание: хранит plain текст ресурса
> Детали: 
> 1. максимальная длина 1023 символа
> 2. не удаляет тэги форматирования текста, например, <b>жирный текст</b>

> Свойство: `id` 
> Тип: `Long`
> Описание: хранит внутренний идентификатор ресурса
> Детали: 
> 1. гарантируется, что он уникален для каждого ресурса

Не стесняйтесь предлагать что угодно, детали обсудим

**Comment by YawKar** [comment]
# **Дедлайн 15 ноября**

**Comment by RandomName-proj** [comment]
Свойство: `parent`
Тип: `Catalog`
Описание: хранит указатель на родительский каталог
Детали:    
  1. не должен быть null

Свойство: `files`
Тип: массив типа, который может хранить файлы
Описание: хранит массив файлов или указателей на файлы

**Comment by midavuha1** [comment]
Свойство: cover
Тип: image
Описание: хранит обложку ресурса
Детали:
    
        1. Наверное должен быть определенного формата хранения данных.
        2. Ограничение по весу

**Comment by YawKar** [comment]
# Итоговая сущность ресурса.

Resource {
  Long id;
  Catalog parent;
  String title;
  String content;
  List<File> files;
  File cover;
}
