### ISSUE TITLE
Внедрить сервисы `service.impl.*` в контроллеры `controller.*`

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-server#16]
1. Повесить `@RequiredArgsConstructor` на оба контроллера в пакете `controller.*`
2. В контроллере `SectionsController`:
   1. Создать поле `final SectionsService sectionsService;` (именно интерфейс!)
   2. Реализовать методы, пользуясь методами `sectionsService`
3. В контроллере `ResourcesController`:
   1. Создать поле `final ResourcesService resourcesService;` (именно интерфейс!)
   2. Реализовать методы, пользуясь методами `resourcesService`

**Comment by RandomName-proj** [comment]
решено в 482d8116b7b3a8e21804bf523765623ea9e4e346
