### ISSUE TITLE
Добавить функционал, возвращающий корневые секции (без родителей)

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-server#21]
Нужно добавить ручки, возвращающие список объектов, у которых родитель == NULL, то есть вернуть корни.

- [x] В интерфейс `SectionRepository` добавить метод, возвращающий `List<SectionEntity>`, у которых `(SQL) parent_section_id = NULL`:
```java
List<SectionEntity> getAllByParentIsNull(); // Spring сам прочитает название метода и реализует его при запуске
```

- [x] В `SectionsService` интерфейсе надо добавить метод, который возвращает `List<PlainSectionDTO>`, ничего в себя не принимает, назвать надо по примеру других методов в интерфейсе.

- [x] В `SectionsServiceImpl` нужно написать реализацию этого нового метода, пользуясь новым методом в `SectionRepository`, не забыть преобразовать каждую сущность в `PlainSectionDTO`

- [x] В `SectionsController` нужно добавить метод, который будет сидеть на `/sections/roots` (внимание, над классом уже стоит часть маппинга), он должен будет возвращать `List<PlainSectionDTO>`

**Comment by RandomName-proj** [comment]
решено в 73207b1ba38479ea9f646f5563ddf86e9e1b4b97
