### ISSUE TITLE
Почистить сущности аннотациями ломбока, чтобы они были проще

### ISSUE THREAD

**Issue by YawKar** [Haermeus-DevGroup/haermeus-server#6]
# Задание

1. Нужно прописать в зависимости проекта (pom.xml) зависимость org.projectlombok.lombok какой-нибудь последней версии, после этого обновить maven проект (правый клик на pom.xml -> обновить что-то там maven).

2. Повесить на все сущности аннотации ломбока для сеттеров, геттеров, дефолтных конструкторов (без аргументов), конструкторов со всеми аргументами, equals & hashcode (тут внимательно, добавить условие, чтобы сравнивались только простые члены сущности (String, Integer и другие примитивы), то есть надо найти в документации ломбока https://projectlombok.org/features/ Exclude аннотации, которыми надо пометить непростые члены сущности (списки и другие сущности)). Также добавить аннотацию, которая сама toString соберёт, но опять-таки пускай собирает только простые члены сущности (опять надо найти Exclude аннотации для ToString).

3. Удалить ненужные методы (сеттеры, геттеры, конструкторы, toString, equals, hashcode), которые теперь заменены аннотациями

# Дедлайн
7 декабря

**Comment by RandomName-proj** [comment]
решил в 5c8301143452f96e0ad0539a9c34bc75ca290be7
